properties:
  global: &config-global
    friendRequestEmailSubject: socialeggbox - Friend Request
    mailSmtpHost: smtp.gmail.com
    mailSmtpSocketFactoryPort: 465
    mailSmtpSocketFactoryClass: javax.net.ssl.SSLSocketFactory
    mailSmtpAuth: true
    mailSmtpPort: 465
    mailUsername: derekclark1971@gmail.com
    mailPassword: $google_password$
    facebookProtectedResourceUrl: https://graph.facebook.com/me
    facebookOauthUrl: https://www.facebook.com/dialog/oauth

environments:
  local: &config-local
    <<: *config-global
    databaseUrl: jdbc:mysql://localhost:3306/socialeggbox
    databaseUsername: derekclark14
    databasePassword: $databasePassword$

    facebookApiKey: $facebookApiKey$
    facebookApiSecret: $facebookApiSecret$
    facebookCallback: http://facebook.derek.com:8080/facebook
    facebookLogoutUrl: http://facebook.derek.com:8080/logout
    facebookLoginUrl: https://www.facebook.com/dialog/oauth?client_id=$facebookApiKey$&redirect_uri=http://facebook.derek.com:8080/facebook&auth_type=rerequest& scope=email

  aws: &config-aws
    <<: *config-global
    databaseUrl: jdbc:mysql://aaaalkh51qagdi.cvb1vcfvd6jj.eu-west-1.rds.amazonaws.com
    databaseUsername: socialcalendar
    databasePassword: $databasePassword$

    facebookApiKey: $facebookApiKey$
    facebookApiSecret: $facebookApiSecret$
    facebookCallback: http://tomcat-env.eu-west-1.elasticbeanstalk.com/facebook
    facebookLogoutUrl: http://tomcat-env.eu-west-1.elasticbeanstalk.com/logout
    facebookLoginUrl: https://www.facebook.com/dialog/oauth?client_id=$facebookApiKey$&redirect_uri=http://tomcat-env.eu-west-1.elasticbeanstalk.com/facebook&auth_type=rerequest& scope=email


  redhat: &config-redhat
    <<: *config-global
    databaseUrl: jdbc:mysql://127.2.43.130:3306/jbossews
    databaseUsername: adminGhDicM9
    databasePassword: $databasePassword$

    facebookApiKey: $facebookApiKey$
    facebookApiSecret: $facebookApiSecret$
    facebookCallback: http://jbossews-socialcalendar.rhcloud.com/facebook
    facebookLogoutUrl: http://jbossews-socialcalendar.rhcloud.com/logout
    facebookLoginUrl: https://www.facebook.com/dialog/oauth?client_id=$facebookApiKey$&redirect_uri=http://jbossews-socialcalendar.rhcloud.com/facebook&auth_type=rerequest& scope=email
